#!/bin/bash

set -e

# go someplace public
cd /tmp 

USER=${1-$(id -nu)}
MMLSQUOTA="/usr/lpp/mmfs/bin/mmlsquota --block-size auto"
FORMAT="%-7s %-16s %8s %8s %8s %8s %1s %8s %8s %8s %8s\n"

if [ $(id -ng) == "ccvstaff" ]; then
    MMLSQUOTA="sudo $MMLSQUOTA"
fi

echo "                   Block Limits                              |           File Limits              "
printf "$FORMAT" Type Filesystem Used Quota HLIMIT Grace \|  Files Quota HLIMIT Grace
echo "-------------------------------------------------------------|----------------------------------------------"

#Filesystem type             KB      quota      limit   in_doubt    grace |    files   quota    limit in_doubt    grace  Remarks
#home       USR        38888648   10485760   50020864          0  35 days |   127505  524288  1048576        0     none oscar.cit

FIELDS="\$2, \$1, \$3, \$4, \$5, \$7, \"|\", \$9, \$10, \$11, \$13"
$MMLSQUOTA -u $USER home  | sed -e 's/ hours/hours/' -e 's/ days/days/' -e 's/none/-/g' | awk "/USR/{printf \"$FORMAT\", $FIELDS;}"

FIELDS="\$3, \$2, \$4, \$5, \$6, \$8, \"|\", \$10, \$11, \$12, \$14"
$MMLSQUOTA -u $USER  gpfs:scratch | sed -e 's/ hours/hours/' -e 's/ days/days/' -e 's/none/-/g' | awk "/USR/{printf \"$FORMAT\", $FIELDS;}"

#
FIELDS="\$2, \$1, \$3, \$4, \$5, \$7, \"|\", \$9, \$10, \$11, \$13"
for GROUP in $(id -nG $USER)
do
if [  -d /gpfs/data/$GROUP ] ; then 
    FIELDS="\$2, \"data+$GROUP\", \$3, \$4, \$5, \$7, \"|\", \$9, \$10, \$11, \$13"
    /usr/lpp/mmfs/bin/mmlsquota -j data+$GROUP --block-size auto gpfs 2>&1 |  sed -e 's/ hours/hours/' -e 's/ days/days/' -e 's/none/-/g' | awk "/FILESET/{printf \"$FORMAT\", $FIELDS;}"
fi
done
