#!/bin/bash

if [ $# -gt 0 ] && [ $1  == h ]; then echo "
jobid,partition,username,nodelist,qos,account,minmemory,eligibletime,starttime,endtime,cores,cpuspertask,reasonlist,name
"
exit
fi

echo jobid,partition,username,nodelist,qos,account,minmemory,eligibletime,starttime,endtime,cores,cpuspertask,reasonlist,name
squeue -O jobid,partition,username,nodelist,qos,account,minmemory,eligibletime,starttime,endtime,cores,cpuspertask,reasonlist,name
#,reasonlist,premptime

#1134460             EMB                 jurban                                  normal              emb-memex           5G                  
#2018-12-09T13:29:29 2019-12-04T08:56:20 NONE                *                   1                   (Resources)         stringtie-sciara-fal
